routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/map', 'MapController@index')->name('map')->middleware(['auth']);

Route::resource('microcontrollers', 'MicrocontrollerController')->middleware(['auth']);

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="container-fluid">
                        <div class="card-deck">
                            <div class="card bg-dark text-light">
                                <div class="card-body text-center">
                                    <div>
                                        <span class="mdi mdi-48px mdi-raspberrypi"></span>
                                    </div>
                                    <p class="card-text">
                                        Add, edit, remove microcontrollers from the system
                                    </p>
                                    <a href="{{route('microcontrollers.index')}}" class="btn btn-yellow">Manage Microcontrollers</a>
                                </div>
                            </div>
                            <div class="card bg-dark text-light">
                                <div class="card-body text-center">
                                    <div>
                                        <span class="mdi mdi-map mdi-48px"></span>
                                    </div>
                                    <p class="card-text">
                                        View microcontrollers and current data on map
                                    </p>
                                    <a href="{{route('map')}}" class="btn btn-yellow">Map</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection